#!/bin/sh
exec ${GUILE-guile} -s $0 "$@" # -*- scheme -*-
!#
(use-modules (scripts doc-snarf))
(read-hash-extend #\& (lambda (c port) (symbol->keyword (read port))))
(apply doc-snarf (cdr (command-line)))
